apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod-label #note: matchLabels is not used
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # nginx listens on port 80, if you want to change, you will need to edit the nginx config in the pod.
      nodePort: 30007
  type: NodePort