apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-pod-label #note: matchLabels is not used
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30007
  type: NodePort